### ISSUE TITLE
Admin - Create Customer

### ISSUE THREAD

**Issue by AmooAti** [AmooAti/Antimorph-ECommerce#6]
## Story
As an admin, I Want to create a customer

### API
Method: POST
Endpoint `api/admin/customer`
Auth: `admin`
Request: `FirstName`, `LastName`, `Email`,`Is Suspend (optional - default active)`, `Phone Number (optional)`, `Password`
Response: 
    - customer model except password field

#### Checklist
- [x] API Doc
- [x] Test

**Comment by parhaaam** [comment]
Auth: `admin`  is not implemented due to it was not ready
